<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountryRegionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country_regions', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedBigInteger('country_id');
            $table->string('name')->nullable();
            $table->timestamps();
        });
        $angola= [
            ['name'=>'Bengo','country_id'=>6],
            ['name'=>'Benguela','country_id'=>6],
            ['name'=>'Bié','country_id'=>6],
            ['name'=>'Cabinda','country_id'=>6],
            ['name'=>'Cuando Cubango','country_id'=>6],
            ['name'=>'Cuanza Norte','country_id'=>6],
            ['name'=>'Cuanza Sul','country_id'=>6],
            ['name'=>'Cunene','country_id'=>6],
            ['name'=>'Huambo','country_id'=>6],
            ['name'=>'Huíla','country_id'=>6],
            ['name'=>'Uíge','country_id'=>6],
            ['name'=>'Luanda','country_id'=>6],
            ['name'=>'Lunda Norte','country_id'=>6],
            ['name'=>'Lunda Sul','country_id'=>6],
            ['name'=>'Malanje','country_id'=>6],
            ['name'=>'Moxico','country_id'=>6],
            ['name'=>'Namibe','country_id'=>6],
            ['name'=>'Zaire','country_id'=>6],
        ]; 


        $Bosnia_and_Herzegowina=[
            ['name'=>'Federation of Bosnia and Herzegovina','country_id'=>27],
             ['name'=>'Republika Srpska','country_id'=>27],
            ['name'=>'Brčko District','country_id'=>27],
        ];
             
             $brazil=[
             ['name'=>'Acre','country_id'=>30],
             ['name'=>'Alagoas','country_id'=>30],
             ['name'=>'Amapá','country_id'=>30],
             ['name'=>'Amazonas','country_id'=>30],
             ['name'=>'Bahia','country_id'=>30],
             ['name'=>'Ceará','country_id'=>30],
             ['name'=>'Distrito Federal','country_id'=>30],
             ['name'=>'Espírito Santo','country_id'=>30],
             ['name'=>'Goiás','country_id'=>30],
             ['name'=>'Maranhão','country_id'=>30],
             ['name'=>'Mato Grosso','country_id'=>30],
             ['name'=>'Mato Grosso do Sul','country_id'=>30],
             ['name'=>'Minas Gerais','country_id'=>30],
             ['name'=>'Pará','country_id'=>30],
             ['name'=>'Paraíba','country_id'=>30],
             ['name'=>'Paraná','country_id'=>30],
             ['name'=>'Pernambuco','country_id'=>30],
             ['name'=>'Piauí','country_id'=>30],
             ['name'=>'Rio de Janeiro','country_id'=>30],
             ['name'=>'Rio Grande do Norte','country_id'=>30],
             ['name'=>'Rio Grande do Sul','country_id'=>30],
             ['name'=>'Rondônia','country_id'=>30],
             ['name'=>'Roraima','country_id'=>30],
             ['name'=>'Santa Catarina','country_id'=>30],
             ['name'=>'São Paulo','country_id'=>30],
             ['name'=>'Sergipe','country_id'=>30],
             ['name'=>'Tocantins','country_id'=>30],
             ];
             
             $cdr = [
             ['name'=>'Kinshasa','country_id'=>49],
             ];
            
            $denmark = [
            ['name'=>'Byen København','country_id'=>57],
             ['name'=>'Københavns omegn','country_id'=>57],
             ['name'=>'Nordsjælland','country_id'=>57],
             ['name'=>'Bornholm','country_id'=>57],
             ['name'=>'Region Sjælland','country_id'=>57],
             ['name'=>'Vest- og Sydsjælland','country_id'=>57],
             ['name'=>'Region Syddanmark','country_id'=>57],
             ['name'=>'Sydjylland','country_id'=>57],
             ['name'=>'Region Midtjylland','country_id'=>57],
             ['name'=>'Østjylland','country_id'=>57],
             ['name'=>'Region Nordjylland','country_id'=>57],
            ];
            
            
            $france = [
            ['name'=>'Auvergne-Rhône-Alpes','country_id'=>73],
             ['name'=>'Bourgogne-Franche-Comté','country_id'=>73],
             ['name'=>'Brittany','country_id'=>73],
             ['name'=>'Centre-Val de Loire','country_id'=>73],
             ['name'=>'Corsica','country_id'=>73],
             ['name'=>'French Guiana','country_id'=>73],
             ['name'=>'Guadeloupe','country_id'=>73],
             ['name'=>'Grand Est','country_id'=>73],
             ['name'=>'Hauts-de-France','country_id'=>73],
             ['name'=>'Île-de-France','country_id'=>73],
             ['name'=>'Martinique','country_id'=>73],
             ['name'=>'Mayotte','country_id'=>73],
             ['name'=>'Normandy','country_id'=>73],
             ['name'=>'Nouvelle-Aquitaine','country_id'=>73],
             ['name'=>'Occitanie','country_id'=>73],
             ['name'=>'Pays de la Loire','country_id'=>73],
             ['name'=>'Provence-Alpes-Côte dAzur','country_id'=>73],
             ['name'=>'Réunion','country_id'=>73],
            ];
            
            $germany = [
            
            ['name'=>'Baden-Württemberg','country_id'=>81],
             ['name'=>'Bavaria','country_id'=>81],
             ['name'=>'Berlin','country_id'=>81],
             ['name'=>'Brandenburg','country_id'=>81],
             ['name'=>'Bremen','country_id'=>81],
             ['name'=>'Hamburg','country_id'=>81],
             ['name'=>'Hessen','country_id'=>81],
             ['name'=>'Niedersachsen','country_id'=>81],
             ['name'=>'Mecklenburg-Vorpommern','country_id'=>81],
             ['name'=>'Nordrhein-Westfalen','country_id'=>81],
             ['name'=>'Rheinland-Pfalz','country_id'=>81],
             ['name'=>'Saarland','country_id'=>81],
             ['name'=>'Sachsen','country_id'=>81],
             ['name'=>'Sachsen-Anhalt','country_id'=>81],
             ['name'=>'Schleswig-Holstein','country_id'=>81],
             ['name'=>'Thüringen','country_id'=>81],
            
            ];
            
            $guinea_busia = [
            ['name'=>'Bafatá','country_id'=>91],
            ['name'=>'Biombo','country_id'=>91],
            ['name'=>'Bissau','country_id'=>91],
            ['name'=>'Bolama','country_id'=>91],
            ['name'=>'Cacheu','country_id'=>91],
            ['name'=>'Gabu','country_id'=>91],
            ['name'=>'Oio','country_id'=>91],
            ['name'=>'Quinara','country_id'=>91],
            ['name'=>'Tombali','country_id'=>91],
            ];
            
            
            $mecedonia = [
            ['name'=>'Skopje','country_id'=>126],];
            
            
            $malta = [
            ['name'=>'Southern Harbour District','country_id'=>132],
             ['name'=>'Northern Harbour District','country_id'=>132],
             ['name'=>'South Eastern District','country_id'=>132],
             ['name'=>'Western District','country_id'=>132],
             ['name'=>'Northern District','country_id'=>132],
             ['name'=>'Gozo and Comino District','country_id'=>132],];
            
            $mexico = [
            ['name'=>'Baja California','country_id'=>138],
             ['name'=>'Baja California Sur','country_id'=>138],
             ['name'=>'Chihuahua','country_id'=>138],
             ['name'=>'Durango','country_id'=>138],
             ['name'=>'Sinaloa','country_id'=>138],
             ['name'=>'Sonora','country_id'=>138],
             ['name'=>'Nordeste','country_id'=>138],
             ['name'=>'Coahuila','country_id'=>138],
             ['name'=>'Nuevo León','country_id'=>138],
             ['name'=>'Tamaulipas','country_id'=>138],
             ['name'=>'Zacatecas','country_id'=>138],
             ['name'=>'Centro-norte','country_id'=>138],
             ['name'=>'Aguascalientes','country_id'=>138],
             ['name'=>'Guanajuato','country_id'=>138],
             ['name'=>'Querétaro','country_id'=>138],
             ['name'=>'San Luis Potos','country_id'=>138],
             ['name'=>'Centro-sul','country_id'=>138],
             ['name'=>'Cidade do México','country_id'=>138],
             ['name'=>'México','country_id'=>138],
             ['name'=>'Morelos','country_id'=>138],
             ['name'=>'Oeste','country_id'=>138],
             ['name'=>'Colima','country_id'=>138],
             ['name'=>'Jalisco','country_id'=>138],
             ['name'=>'Michoacán','country_id'=>138],
             ['name'=>'Nayarit','country_id'=>138],
             ['name'=>'Leste','country_id'=>138],
             ['name'=>'Hidalgo','country_id'=>138],
             ['name'=>'Puebla','country_id'=>138],
             ['name'=>'Tlaxcala','country_id'=>138],
             ['name'=>'Veracruz','country_id'=>138],
             ['name'=>'Sudeste','country_id'=>138],
             ['name'=>'Campeche','country_id'=>138],
             ['name'=>'Quintana Roo','country_id'=>138],
             ['name'=>'Tabasco','country_id'=>138],
             ['name'=>'Yucatán','country_id'=>138],
             ['name'=>'Sudoeste','country_id'=>138],
             ['name'=>'Chiapas','country_id'=>138],
             ['name'=>'Guerrero','country_id'=>138],
             ['name'=>'Oaxaca','country_id'=>138],
            ];
            
            $mazuk = [
            ['name'=>'Cabo Delgado','country_id'=>145],
             ['name'=>'Cidade de Maputo','country_id'=>145],
             ['name'=>'Gaza','country_id'=>145],
             ['name'=>'Inhambane','country_id'=>145],
             ['name'=>'Manica','country_id'=>145],
             ['name'=>'Maputo','country_id'=>145],
             ['name'=>'Nampula','country_id'=>145],
             ['name'=>'Niassa','country_id'=>145],
             ['name'=>'Sofala','country_id'=>145],
             ['name'=>'Tete','country_id'=>145],
             ['name'=>'Zambézia','country_id'=>145],
            
            ];
            
            $nigeria = [
            
            ['name'=>'Abia','country_id'=>156],
             ['name'=>'Adamawa','country_id'=>156],
             ['name'=>'Akwa Ibom','country_id'=>156],
             ['name'=>'Anambra','country_id'=>156],
             ['name'=>'Bauchi','country_id'=>156],
             ['name'=>'Bayelsa','country_id'=>156],
             ['name'=>'Benue','country_id'=>156],
             ['name'=>'Borno','country_id'=>156],
             ['name'=>'Cross River','country_id'=>156],
             ['name'=>'Delta','country_id'=>156],
             ['name'=>'Ebonyi','country_id'=>156],
             ['name'=>'Enugu','country_id'=>156],
             ['name'=>'Edo','country_id'=>156],
             ['name'=>'Ekiti','country_id'=>156],
             ['name'=>'Gombe','country_id'=>156],
             ['name'=>'Imo','country_id'=>156],
             ['name'=>'Jigawa','country_id'=>156],
             ['name'=>'Kaduna','country_id'=>156],
             ['name'=>'Kano','country_id'=>156],
             ['name'=>'Katsina','country_id'=>156],
             ['name'=>'Kebbi','country_id'=>156],
             ['name'=>'Kogi','country_id'=>156],
             ['name'=>'Kwara','country_id'=>156],
             ['name'=>'Lagos','country_id'=>156],
             ['name'=>'Nasarawa','country_id'=>156],
             ['name'=>'Niger','country_id'=>156],
             ['name'=>'Ogun','country_id'=>156],
             ['name'=>'Ondo','country_id'=>156],
             ['name'=>'Osun','country_id'=>156],
             ['name'=>'Oyo','country_id'=>156],
             ['name'=>'Plateau','country_id'=>156],
             ['name'=>'Rivers','country_id'=>156],
             ['name'=>'Sokoto','country_id'=>156],
             ['name'=>'Taraba','country_id'=>156],
             ['name'=>'Yobe','country_id'=>156],
             ['name'=>'Zamfara','country_id'=>156],
            ];
            
            $norway = [
            
            ['name'=>'Østfold','country_id'=>160],
             ['name'=>'Akershus','country_id'=>160],
             ['name'=>'Oslo','country_id'=>160],
             ['name'=>'Hedmark','country_id'=>160],
             ['name'=>'Oppland','country_id'=>160],
             ['name'=>'Buskerud','country_id'=>160],
             ['name'=>'Vestfold','country_id'=>160],
             ['name'=>'Telemark','country_id'=>160],
             ['name'=>'Aust-Agder','country_id'=>160],
             ['name'=>'Vest-Agder','country_id'=>160],
             ['name'=>'Rogaland','country_id'=>160],
             ['name'=>'Hordaland','country_id'=>160],
             ['name'=>'Sogn og Fjordane','country_id'=>160],
             ['name'=>'Møre og Romsdal','country_id'=>160],
             ['name'=>'Trøndelag','country_id'=>160],
             ['name'=>'Nordland','country_id'=>160],
             ['name'=>'Troms','country_id'=>160],
             ['name'=>'Finnmark','country_id'=>160],
            ];
            
            
            $purtogal = [
            ['name'=>'Abrantes','country_id'=>171],
             ['name'=>'Açores','country_id'=>171],
             ['name'=>'Águeda','country_id'=>171],
             ['name'=>'Aguiar da Beira','country_id'=>171],
             ['name'=>'Alandroal','country_id'=>171],
             ['name'=>'Albergaria-a-Velha','country_id'=>171],
             ['name'=>'Albufeira','country_id'=>171],
             ['name'=>'Alcácer do Sal','country_id'=>171],
             ['name'=>'Alcanena','country_id'=>171],
             ['name'=>'Alcobaça','country_id'=>171],
             ['name'=>'Alcochete','country_id'=>171],
             ['name'=>'Alcoutim','country_id'=>171],
             ['name'=>'Alenquer','country_id'=>171],
             ['name'=>'Alfândega da Fé','country_id'=>171],
             ['name'=>'Alijó','country_id'=>171],
             ['name'=>'Aljezur','country_id'=>171],
             ['name'=>'Aljustrel','country_id'=>171],
             ['name'=>'Almada','country_id'=>171],
             ['name'=>'Almeida','country_id'=>171],
             ['name'=>'Almeirim','country_id'=>171],
             ['name'=>'Almodôvar','country_id'=>171],
             ['name'=>'Alpiarça','country_id'=>171],
             ['name'=>'Alter do Chão','country_id'=>171],
             ['name'=>'Alvaiázere','country_id'=>171],
             ['name'=>'Alvito','country_id'=>171],
             ['name'=>'Amadora','country_id'=>171],
             ['name'=>'Amarante','country_id'=>171],
             ['name'=>'Amares','country_id'=>171],
             ['name'=>'Anadia','country_id'=>171],
             ['name'=>'Angra do Heroísmo','country_id'=>171],
             ['name'=>'Ansião','country_id'=>171],
             ['name'=>'Arcos de Valdevez','country_id'=>171],
             ['name'=>'Arganil','country_id'=>171],
             ['name'=>'Armamar','country_id'=>171],
             ['name'=>'Arouca','country_id'=>171],
             ['name'=>'Arraiolos','country_id'=>171],
             ['name'=>'Arronches','country_id'=>171],
             ['name'=>'Arruda dos Vinhos','country_id'=>171],
             ['name'=>'Aveiro','country_id'=>171],
             ['name'=>'Avis','country_id'=>171],
             ['name'=>'Azambuja','country_id'=>171],
             ['name'=>'Baião','country_id'=>171],
             ['name'=>'Barcelos','country_id'=>171],
             ['name'=>'Barrancos','country_id'=>171],
             ['name'=>'Barreiro','country_id'=>171],
             ['name'=>'Batalha','country_id'=>171],
             ['name'=>'Beja','country_id'=>171],
             ['name'=>'Belmonte','country_id'=>171],
             ['name'=>'Benavente','country_id'=>171],
             ['name'=>'Bombarral','country_id'=>171],
             ['name'=>'Borba','country_id'=>171],
             ['name'=>'Boticas','country_id'=>171],
             ['name'=>'Braga','country_id'=>171],
             ['name'=>'Bragança','country_id'=>171],
             ['name'=>'Cabeceiras de Basto','country_id'=>171],
             ['name'=>'Cadaval','country_id'=>171],
             ['name'=>'Caldas da Rainha','country_id'=>171],
             ['name'=>'Calheta (Madeira)','country_id'=>171],
             ['name'=>'Calheta (São Jorge)','country_id'=>171],
             ['name'=>'Caminha','country_id'=>171],
             ['name'=>'Campo Maior','country_id'=>171],
             ['name'=>'Cantanhede','country_id'=>171],
             ['name'=>'Carrazeda de Ansiães','country_id'=>171],
             ['name'=>'Carregal do Sal','country_id'=>171],
             ['name'=>'Cartaxo','country_id'=>171],
             ['name'=>'Cascais','country_id'=>171],
             ['name'=>'Castanheira de Pêra','country_id'=>171],
             ['name'=>'Castelo Branco','country_id'=>171],
             ['name'=>'Castelo de Paiva','country_id'=>171],
             ['name'=>'Castelo de Vide','country_id'=>171],
             ['name'=>'Castro Daire','country_id'=>171],
             ['name'=>'Castro Marim','country_id'=>171],
             ['name'=>'Castro Verde','country_id'=>171],
             ['name'=>'Celorico da Beira','country_id'=>171],
             ['name'=>'Celorico de Basto','country_id'=>171],
             ['name'=>'Chamusca','country_id'=>171],
             ['name'=>'Chaves','country_id'=>171],
             ['name'=>'Cinfães','country_id'=>171],
             ['name'=>'Coimbra','country_id'=>171],
             ['name'=>'Condeixa-a-Nova','country_id'=>171],
             ['name'=>'Constância','country_id'=>171],
             ['name'=>'Coruche','country_id'=>171],
             ['name'=>'Corvo','country_id'=>171],
             ['name'=>'Covilhã','country_id'=>171],
             ['name'=>'Crato','country_id'=>171],
             ['name'=>'Cuba','country_id'=>171],
             ['name'=>'Câmara de Lobos','country_id'=>171],
             ['name'=>'Elvas','country_id'=>171],
             ['name'=>'Entroncamento','country_id'=>171],
             ['name'=>'Espinho','country_id'=>171],
             ['name'=>'Esposende','country_id'=>171],
             ['name'=>'Estarreja','country_id'=>171],
             ['name'=>'Estremoz','country_id'=>171],
             ['name'=>'Évora','country_id'=>171],
             ['name'=>'Fafe','country_id'=>171],
             ['name'=>'Faro','country_id'=>171],
             ['name'=>'Felgueiras','country_id'=>171],
             ['name'=>'Ferreira do Alentejo','country_id'=>171],
             ['name'=>'Ferreira do Zêzere','country_id'=>171],
             ['name'=>'Figueira da Foz','country_id'=>171],
             ['name'=>'Figueira de Castelo Rodrigo','country_id'=>171],
             ['name'=>'Figueiró dos Vinhos','country_id'=>171],
             ['name'=>'Fornos de Algodres','country_id'=>171],
             ['name'=>'Freixo de Espada à Cinta','country_id'=>171],
             ['name'=>'Fronteira','country_id'=>171],
             ['name'=>'Funchal','country_id'=>171],
             ['name'=>'Fundão','country_id'=>171],
             ['name'=>'Gavião','country_id'=>171],
             ['name'=>'Golegã','country_id'=>171],
             ['name'=>'Gondomar','country_id'=>171],
             ['name'=>'Gouveia','country_id'=>171],
             ['name'=>'Grândola','country_id'=>171],
             ['name'=>'Guarda','country_id'=>171],
             ['name'=>'Guimarães','country_id'=>171],
             ['name'=>'Góis','country_id'=>171],
             ['name'=>'Horta','country_id'=>171],
             ['name'=>'Idanha-a-Nova','country_id'=>171],
             ['name'=>'Ílhavo','country_id'=>171],
             ['name'=>'Lagoa (Algarve)','country_id'=>171],
             ['name'=>'Lagoa (São Miguel)','country_id'=>171],
             ['name'=>'Lagos','country_id'=>171],
             ['name'=>'Lajes das Flores','country_id'=>171],
             ['name'=>'Lajes do Pico','country_id'=>171],
             ['name'=>'Lamego','country_id'=>171],
             ['name'=>'Leiria','country_id'=>171],
             ['name'=>'Lisboa','country_id'=>171],
             ['name'=>'Loulé','country_id'=>171],
             ['name'=>'Loures','country_id'=>171],
             ['name'=>'Lourinhã','country_id'=>171],
             ['name'=>'Lousã','country_id'=>171],
             ['name'=>'Lousada','country_id'=>171],
             ['name'=>'Mação','country_id'=>171],
             ['name'=>'Macedo de Cavaleiros','country_id'=>171],
             ['name'=>'Machico','country_id'=>171],
             ['name'=>'Madalena','country_id'=>171],
             ['name'=>'Madeira','country_id'=>171],
             ['name'=>'Mafra','country_id'=>171],
             ['name'=>'Maia','country_id'=>171],
             ['name'=>'Mangualde','country_id'=>171],
             ['name'=>'Manteigas','country_id'=>171],
             ['name'=>'Marco de Canaveses','country_id'=>171],
             ['name'=>'Marinha Grande','country_id'=>171],
             ['name'=>'Marvão','country_id'=>171],
             ['name'=>'Matosinhos','country_id'=>171],
             ['name'=>'Mealhada','country_id'=>171],
             ['name'=>'Meda','country_id'=>171],
             ['name'=>'Melgaço','country_id'=>171],
             ['name'=>'Mesão Frio','country_id'=>171],
             ['name'=>'Mira','country_id'=>171],
             ['name'=>'Miranda do Corvo','country_id'=>171],
             ['name'=>'Miranda do Douro','country_id'=>171],
             ['name'=>'Mirandela','country_id'=>171],
             ['name'=>'Mogadouro','country_id'=>171],
             ['name'=>'Moimenta da Beira','country_id'=>171],
             ['name'=>'Moita','country_id'=>171],
             ['name'=>'Monção','country_id'=>171],
             ['name'=>'Monchique','country_id'=>171],
             ['name'=>'Mondim de Basto','country_id'=>171],
             ['name'=>'Monforte','country_id'=>171],
             ['name'=>'Montalegre','country_id'=>171],
             ['name'=>'Montemor-o-Novo','country_id'=>171],
             ['name'=>'Montemor-o-Velho','country_id'=>171],
             ['name'=>'Montijo','country_id'=>171],
             ['name'=>'Mora','country_id'=>171],
             ['name'=>'Mortágua','country_id'=>171],
             ['name'=>'Moura','country_id'=>171],
             ['name'=>'Mourão','country_id'=>171],
             ['name'=>'Murça','country_id'=>171],
             ['name'=>'Murtosa','country_id'=>171],
             ['name'=>'Mértola','country_id'=>171],
             ['name'=>'Nazaré','country_id'=>171],
             ['name'=>'Nelas','country_id'=>171],
             ['name'=>'Nisa','country_id'=>171],
             ['name'=>'Nordeste','country_id'=>171],
             ['name'=>'Óbidos','country_id'=>171],
             ['name'=>'Odemira','country_id'=>171],
             ['name'=>'Odivelas','country_id'=>171],
             ['name'=>'Oeiras','country_id'=>171],
             ['name'=>'Oleiros','country_id'=>171],
             ['name'=>'Olhão','country_id'=>171],
             ['name'=>'Oliveira de Azeméis','country_id'=>171],
             ['name'=>'Oliveira de Frades','country_id'=>171],
             ['name'=>'Oliveira do Bairro','country_id'=>171],
             ['name'=>'Oliveira do Hospital','country_id'=>171],
             ['name'=>'Ourique','country_id'=>171],
             ['name'=>'Ourém','country_id'=>171],
             ['name'=>'Ovar','country_id'=>171],
             ['name'=>'Paços de Ferreira','country_id'=>171],
             ['name'=>'Palmela','country_id'=>171],
             ['name'=>'Pampilhosa da Serra','country_id'=>171],
             ['name'=>'Paredes','country_id'=>171],
             ['name'=>'Paredes de Coura','country_id'=>171],
             ['name'=>'Pedrógão Grande','country_id'=>171],
             ['name'=>'Penacova','country_id'=>171],
             ['name'=>'Penafiel','country_id'=>171],
             ['name'=>'Penalva do Castelo','country_id'=>171],
             ['name'=>'Penamacor','country_id'=>171],
             ['name'=>'Penedono','country_id'=>171],
             ['name'=>'Penela','country_id'=>171],
             ['name'=>'Peniche','country_id'=>171],
             ['name'=>'Peso da Régua','country_id'=>171],
             ['name'=>'Pinhel','country_id'=>171],
             ['name'=>'Pombal','country_id'=>171],
             ['name'=>'Ponta Delgada','country_id'=>171],
             ['name'=>'Ponta do Sol','country_id'=>171],
             ['name'=>'Ponte da Barca','country_id'=>171],
             ['name'=>'Ponte de Lima','country_id'=>171],
             ['name'=>'Ponte de Sor','country_id'=>171],
             ['name'=>'Portalegre','country_id'=>171],
             ['name'=>'Portel','country_id'=>171],
             ['name'=>'Portimão','country_id'=>171],
             ['name'=>'Porto','country_id'=>171],
             ['name'=>'Porto Moniz','country_id'=>171],
             ['name'=>'Porto Santo','country_id'=>171],
             ['name'=>'Porto de Mós','country_id'=>171],
             ['name'=>'Povoação','country_id'=>171],
             ['name'=>'Praia da Vitória','country_id'=>171],
             ['name'=>'Proença-a-Nova','country_id'=>171],
             ['name'=>'Póvoa de Lanhoso','country_id'=>171],
             ['name'=>'Póvoa de Varzim','country_id'=>171],
             ['name'=>'Redondo','country_id'=>171],
             ['name'=>'Reguengos de Monsaraz','country_id'=>171],
             ['name'=>'Resende','country_id'=>171],
             ['name'=>'Ribeira Brava','country_id'=>171],
             ['name'=>'Ribeira Grande','country_id'=>171],
             ['name'=>'Ribeira de Pena','country_id'=>171],
             ['name'=>'Rio Maior','country_id'=>171],
             ['name'=>'Sabrosa','country_id'=>171],
             ['name'=>'Sabugal','country_id'=>171],
             ['name'=>'Salvaterra de Magos','country_id'=>171],
             ['name'=>'Santa Comba Dão','country_id'=>171],
             ['name'=>'Santa Cruz','country_id'=>171],
             ['name'=>'Santa Cruz da Graciosa','country_id'=>171],
             ['name'=>'Santa Cruz das Flores','country_id'=>171],
             ['name'=>'Santa Maria da Feira','country_id'=>171],
             ['name'=>'Santa Marta de Penaguião','country_id'=>171],
             ['name'=>'Santana','country_id'=>171],
             ['name'=>'Santarém','country_id'=>171],
             ['name'=>'Santiago do Cacém','country_id'=>171],
             ['name'=>'Santo Tirso','country_id'=>171],
             ['name'=>'São Brás de Alportel','country_id'=>171],
             ['name'=>'São João da Madeira','country_id'=>171],
             ['name'=>'São João da Pesqueira','country_id'=>171],
             ['name'=>'São Pedro do Sul','country_id'=>171],
             ['name'=>'São Roque do Pico','country_id'=>171],
             ['name'=>'São Vicente','country_id'=>171],
             ['name'=>'Sardoal','country_id'=>171],
             ['name'=>'Sátão','country_id'=>171],
             ['name'=>'Seia','country_id'=>171],
             ['name'=>'Seixal','country_id'=>171],
             ['name'=>'Sernancelhe','country_id'=>171],
             ['name'=>'Serpa','country_id'=>171],
             ['name'=>'Sertã','country_id'=>171],
             ['name'=>'Sesimbra','country_id'=>171],
             ['name'=>'Setúbal','country_id'=>171],
             ['name'=>'Sever do Vouga','country_id'=>171],
             ['name'=>'Silves','country_id'=>171],
             ['name'=>'Sines','country_id'=>171],
             ['name'=>'Sintra','country_id'=>171],
             ['name'=>'Sobral de Monte Agraço','country_id'=>171],
             ['name'=>'Soure','country_id'=>171],
             ['name'=>'Sousel','country_id'=>171],
             ['name'=>'Tábua','country_id'=>171],
             ['name'=>'Tabuaço','country_id'=>171],
             ['name'=>'Tarouca','country_id'=>171],
             ['name'=>'Tavira','country_id'=>171],
             ['name'=>'Terras de Bouro','country_id'=>171],
             ['name'=>'Tomar','country_id'=>171],
             ['name'=>'Tondela','country_id'=>171],
             ['name'=>'Torre de Moncorvo','country_id'=>171],
             ['name'=>'Torres Novas','country_id'=>171],
             ['name'=>'Torres Vedras','country_id'=>171],
             ['name'=>'Trancoso','country_id'=>171],
             ['name'=>'Trofa','country_id'=>171],
             ['name'=>'Vagos','country_id'=>171],
             ['name'=>'Vale de Cambra','country_id'=>171],
             ['name'=>'Valença','country_id'=>171],
             ['name'=>'Valongo','country_id'=>171],
             ['name'=>'Valpaços','country_id'=>171],
             ['name'=>'Velas','country_id'=>171],
             ['name'=>'Vendas Novas','country_id'=>171],
             ['name'=>'Viana do Alentejo','country_id'=>171],
             ['name'=>'Viana do Castelo','country_id'=>171],
             ['name'=>'Vidigueira','country_id'=>171],
             ['name'=>'Vieira do Minho','country_id'=>171],
             ['name'=>'Vila Flor','country_id'=>171],
             ['name'=>'Vila Franca de Xira','country_id'=>171],
             ['name'=>'Vila Franca do Campo','country_id'=>171],
             ['name'=>'Vila Nova da Barquinha','country_id'=>171],
             ['name'=>'Vila Nova de Cerveira','country_id'=>171],
             ['name'=>'Vila Nova de Famalicão','country_id'=>171],
             ['name'=>'Vila Nova de Foz Côa','country_id'=>171],
             ['name'=>'Vila Nova de Gaia','country_id'=>171],
             ['name'=>'Vila Nova de Paiva','country_id'=>171],
             ['name'=>'Vila Nova de Poiares','country_id'=>171],
             ['name'=>'Vila Pouca de Aguiar','country_id'=>171],
             ['name'=>'Vila Real','country_id'=>171],
             ['name'=>'Vila Real de Santo António','country_id'=>171],
             ['name'=>'Vila Velha de Ródão','country_id'=>171],
             ['name'=>'Vila Verde','country_id'=>171],
             ['name'=>'Vila Viçosa','country_id'=>171],
             ['name'=>'Vila de Rei','country_id'=>171],
             ['name'=>'Vila do Bispo','country_id'=>171],
             ['name'=>'Vila do Conde','country_id'=>171],
             ['name'=>'Vila do Porto','country_id'=>171],
             ['name'=>'Vimioso','country_id'=>171],
             ['name'=>'Vinhais','country_id'=>171],
             ['name'=>'Viseu','country_id'=>171],
             ['name'=>'Vizela','country_id'=>171],
             ['name'=>'Vouzela','country_id'=>171],
            ];
            
            
            $spain = [
            ['name'=>'Álava','country_id'=>195],
             ['name'=>'Albacete','country_id'=>195],
             ['name'=>'Alicante','country_id'=>195],
             ['name'=>'Almería','country_id'=>195],
             ['name'=>'Astúrias','country_id'=>195],
             ['name'=>'Ávila','country_id'=>195],
             ['name'=>'Badajoz','country_id'=>195],
             ['name'=>'Ilhas Baleares','country_id'=>195],
             ['name'=>'Barcelona','country_id'=>195],
             ['name'=>'Biscaia','country_id'=>195],
             ['name'=>'Burgos','country_id'=>195],
             ['name'=>'Cáceres','country_id'=>195],
             ['name'=>'Cádis','country_id'=>195],
             ['name'=>'Cantábria','country_id'=>195],
             ['name'=>'Castelló','country_id'=>195],
             ['name'=>'Ceuta','country_id'=>195],
             ['name'=>'Cidade Real','country_id'=>195],
             ['name'=>'Córdova','country_id'=>195],
             ['name'=>'Corunha','country_id'=>195],
             ['name'=>'Cuenca','country_id'=>195],
             ['name'=>'Gerunda','country_id'=>195],
             ['name'=>'Granada','country_id'=>195],
             ['name'=>'Guadalajara','country_id'=>195],
             ['name'=>'Guipúscoa','country_id'=>195],
             ['name'=>'Huelva','country_id'=>195],
             ['name'=>'Huesca','country_id'=>195],
             ['name'=>'Jaén','country_id'=>195],
             ['name'=>'La Rioja','country_id'=>195],
             ['name'=>'León','country_id'=>195],
             ['name'=>'Lérida','country_id'=>195],
             ['name'=>'Lugo','country_id'=>195],
             ['name'=>'Madrid','country_id'=>195],
             ['name'=>'Málaga','country_id'=>195],
             ['name'=>'Melilla','country_id'=>195],
             ['name'=>'Múrcia','country_id'=>195],
             ['name'=>'Navarra','country_id'=>195],
             ['name'=>'Ourense','country_id'=>195],
             ['name'=>'Palência','country_id'=>195],
             ['name'=>'Las Palmas','country_id'=>195],
             ['name'=>'Pontevedra','country_id'=>195],
             ['name'=>'Salamanca','country_id'=>195],
             ['name'=>'Santa Cruz de Tenerife','country_id'=>195],
             ['name'=>'Saragoça','country_id'=>195],
             ['name'=>'Segóvia','country_id'=>195],
             ['name'=>'Sevilha','country_id'=>195],
             ['name'=>'Sória','country_id'=>195],
             ['name'=>'Tarragona','country_id'=>195],
             ['name'=>'Teruel','country_id'=>195],
             ['name'=>'Toledo','country_id'=>195],
             ['name'=>'Valência','country_id'=>195],
             ['name'=>'Valladolid','country_id'=>195],
             ['name'=>'Zamora','country_id'=>195],
            ];
            
            $sweden = [
            ['name'=>'Ångermanland','country_id'=>203],
            ['name'=>'Blekinge','country_id'=>203],
            ['name'=>'Bohuslän','country_id'=>203],
            ['name'=>'Dalarna','country_id'=>203],
            ['name'=>'Dalsland','country_id'=>203],
            ['name'=>'Gotland','country_id'=>203],
            ['name'=>'Gästrikland','country_id'=>203],
            ['name'=>'Halland','country_id'=>203],
            ['name'=>'Hälsingland','country_id'=>203],
            ['name'=>'Härjedalen','country_id'=>203],
            ['name'=>'Jämtland','country_id'=>203],
            ['name'=>'Lappland','country_id'=>203],
            ['name'=>'Medelpad','country_id'=>203],
            ['name'=>'Norrbotten','country_id'=>203],
            ['name'=>'Närke','country_id'=>203],
            ['name'=>'Öland','country_id'=>203],
            ['name'=>'Östergötland','country_id'=>203],
            ['name'=>'Skåne','country_id'=>203],
            ['name'=>'Småland','country_id'=>203],
            ['name'=>'Södermanland','country_id'=>203],
            ['name'=>'Uppland','country_id'=>203],
            ['name'=>'Värmland','country_id'=>203],
            ['name'=>'Västmanland','country_id'=>203],
            ['name'=>'Västerbotten','country_id'=>203],
            ['name'=>'Västergötland','country_id'=>203],
            ];
            
            $uk = [
            ['name'=>'Aberdeen','country_id'=>222],
             ['name'=>'Armagh','country_id'=>222],
             ['name'=>'Bangor','country_id'=>222],
             ['name'=>'Bath','country_id'=>222],
             ['name'=>'Belfast','country_id'=>222],
             ['name'=>'Birmingham','country_id'=>222],
             ['name'=>'Bradford','country_id'=>222],
             ['name'=>'Brighton and Hove','country_id'=>222],
             ['name'=>'Bristol','country_id'=>222],
             ['name'=>'Cambridge','country_id'=>222],
             ['name'=>'Canterbury','country_id'=>222],
             ['name'=>'Cardiff','country_id'=>222],
             ['name'=>'Carlisle','country_id'=>222],
             ['name'=>'Chelmsford','country_id'=>222],
             ['name'=>'Chester','country_id'=>222],
             ['name'=>'Chichester','country_id'=>222],
             ['name'=>'Coventry','country_id'=>222],
             ['name'=>'Derby','country_id'=>222],
             ['name'=>'Dundee','country_id'=>222],
             ['name'=>'Durham','country_id'=>222],
             ['name'=>'Edinburgh','country_id'=>222],
             ['name'=>'Ely','country_id'=>222],
             ['name'=>'Exeter','country_id'=>222],
             ['name'=>'Glasgow','country_id'=>222],
             ['name'=>'Gloucester','country_id'=>222],
             ['name'=>'Hereford','country_id'=>222],
             ['name'=>'Inverness','country_id'=>222],
             ['name'=>'Kingston upon Hull','country_id'=>222],
             ['name'=>'Lancaster','country_id'=>222],
             ['name'=>'Leeds','country_id'=>222],
             ['name'=>'Leicester','country_id'=>222],
             ['name'=>'Lichfield','country_id'=>222],
             ['name'=>'Lincoln','country_id'=>222],
             ['name'=>'Lisburn','country_id'=>222],
             ['name'=>'Liverpool','country_id'=>222],
             ['name'=>'London','country_id'=>222],
             ['name'=>'Londonderry','country_id'=>222],
             ['name'=>'Manchester','country_id'=>222],
             ['name'=>'Newcastle upon Tyne','country_id'=>222],
             ['name'=>'Newport','country_id'=>222],
             ['name'=>'Newry','country_id'=>222],
             ['name'=>'Norwich','country_id'=>222],
             ['name'=>'Nottingham','country_id'=>222],
             ['name'=>'Oxford','country_id'=>222],
             ['name'=>'Perth','country_id'=>222],
             ['name'=>'Peterborough','country_id'=>222],
             ['name'=>'Plymouth','country_id'=>222],
             ['name'=>'Portsmouth','country_id'=>222],
             ['name'=>'Preston','country_id'=>222],
             ['name'=>'Ripon','country_id'=>222],
             ['name'=>'St. Albans','country_id'=>222],
             ['name'=>'St. Asaph','country_id'=>222],
             ['name'=>'St. Davids','country_id'=>222],
             ['name'=>'Salford','country_id'=>222],
             ['name'=>'Salisbury','country_id'=>222],
             ['name'=>'Sheffield','country_id'=>222],
             ['name'=>'Southampton','country_id'=>222],
             ['name'=>'Stirling','country_id'=>222],
             ['name'=>'Stoke-on-Trent','country_id'=>222],
             ['name'=>'Sunderland','country_id'=>222],
             ['name'=>'Swansea','country_id'=>222],
             ['name'=>'Truro','country_id'=>222],
             ['name'=>'Wakefield','country_id'=>222],
             ['name'=>'Wells','country_id'=>222],
             ['name'=>'Westminster','country_id'=>222],
             ['name'=>'Winchester','country_id'=>222],
             ['name'=>'Wolverhampton','country_id'=>222],
             ['name'=>'Worcester','country_id'=>222],
             ['name'=>'York','country_id'=>222],
            ];
            
            $us= [
                ['name'=>'Alabama','country_id'=>223],
                ['name'=>'Alaska','country_id'=>223],
                ['name'=>'Arizona','country_id'=>223],
                ['name'=>'Arkansas','country_id'=>223],
                ['name'=>'California','country_id'=>223],
                ['name'=>'Colorado','country_id'=>223],
                ['name'=>'Connecticut','country_id'=>223],
                ['name'=>'Delaware','country_id'=>223],
                ['name'=>'Florida','country_id'=>223],
                ['name'=>'Georgia','country_id'=>223],
                ['name'=>'Hawaii','country_id'=>223],
                ['name'=>'Idaho','country_id'=>223],
                ['name'=>'Illinois','country_id'=>223],
                ['name'=>'Indiana','country_id'=>223],
                ['name'=>'Iowa','country_id'=>223],
                ['name'=>'Kansas','country_id'=>223],
                ['name'=>'Kentucky','country_id'=>223],
                ['name'=>'Louisiana','country_id'=>223],
                ['name'=>'Maine','country_id'=>223],
                ['name'=>'Maryland','country_id'=>223],
                ['name'=>'Massachusetts','country_id'=>223],
                ['name'=>'Michigan','country_id'=>223],
                ['name'=>'Minnesota','country_id'=>223],
                ['name'=>'Mississippi','country_id'=>223],
                ['name'=>'Missouri','country_id'=>223],
                ['name'=>'Montana','country_id'=>223],
                ['name'=>'Nebraska','country_id'=>223],
                ['name'=>'Nevada','country_id'=>223],
                ['name'=>'New Hampshire','country_id'=>223],
                ['name'=>'New Jersey','country_id'=>223],
                ['name'=>'New Mexico','country_id'=>223],
                ['name'=>'New York','country_id'=>223],
                ['name'=>'North Carolina','country_id'=>223],
                ['name'=>'North Dakota','country_id'=>223],
                ['name'=>'Ohio','country_id'=>223],
                ['name'=>'Oklahoma','country_id'=>223],
                ['name'=>'Oregon','country_id'=>223],
                ['name'=>'Pennsylvania','country_id'=>223],
                ['name'=>'Rhode Island','country_id'=>223],
                ['name'=>'South Carolina','country_id'=>223],
                ['name'=>'South Dakota','country_id'=>223],
                ['name'=>'Tennessee','country_id'=>223],
                ['name'=>'Texas','country_id'=>223],
                ['name'=>'Utah','country_id'=>223],
                ['name'=>'Vermont','country_id'=>223],
                ['name'=>'Virginia','country_id'=>223],
                ['name'=>'Washington','country_id'=>223],
                ['name'=>'West Virginia','country_id'=>223],
                ['name'=>'Wisconsin','country_id'=>223],
                ['name'=>'Wyoming','country_id'=>223],
            
            ];

        DB::table('country_regions')->insert(
            $angola
        );
        
        DB::table('country_regions')->insert(
            $Bosnia_and_Herzegowina
        );
        
        DB::table('country_regions')->insert(
            $cdr
        );
        
        DB::table('country_regions')->insert(
            $france
        );
        
        DB::table('country_regions')->insert(
            $germany
        );
        
        DB::table('country_regions')->insert(
            $guinea_busia
        );
        
        DB::table('country_regions')->insert(
            $mecedonia
        );
        
        DB::table('country_regions')->insert(
            $malta
        );
        
        DB::table('country_regions')->insert(
            $mexico
        );
        
        DB::table('country_regions')->insert(
            $mazuk
        );
        
        DB::table('country_regions')->insert(
            $norway
        );
        
        DB::table('country_regions')->insert(
            $purtogal
        );
        
        DB::table('country_regions')->insert(
            $spain
        );
        
        DB::table('country_regions')->insert(
            $sweden
        );
        
        DB::table('country_regions')->insert(
            $uk
        );
        
        DB::table('country_regions')->insert(
            $us
        );
        DB::table('country_regions')->insert(
            $denmark
        );
        DB::table('country_regions')->insert(
            $nigeria
        );
        DB::table('country_regions')->insert(
            $brazil
        );
       
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country__regions');
    }
}
